#!/bin/bash
f=$(pwd)

sips --resampleWidth 29 "${f}/${1}" --out "${f}/icon29.png"
sips --resampleWidth 58 "${f}/${1}" --out "${f}/icon29@2x.png"
sips --resampleWidth 87 "${f}/${1}" --out "${f}/icon29@3x.png"

sips --resampleWidth 40 "${f}/${1}" --out "${f}/icon40.png"
sips --resampleWidth 80 "${f}/${1}" --out "${f}/icon40@2x.png"
sips --resampleWidth 120 "${f}/${1}" --out "${f}/icon40@3x.png"

sips --resampleWidth 120 "${f}/${1}" --out "${f}/icon60@2x.png"
sips --resampleWidth 180 "${f}/${1}" --out "${f}/icon60@3x.png"

sips --resampleWidth 76 "${f}/${1}" --out "${f}/icon76.png"
sips --resampleWidth 152 "${f}/${1}" --out "${f}/icon76@2x.png"

sips --resampleWidth 512 "${f}/${1}" --out "${f}/iTunesArtwork"
sips --resampleWidth 1024 "${f}/${1}" --out "${f}/iTunesArtwork@2x"